name: Test cicd

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn -i

      - name: Build APK
        run: |
          # npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          cd android
          # ./gradlew clean
          ./gradlew assembleRelease
          # npx react-native run-android --variant=release

      - name: Save APK as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk

  download_apk:
    runs-on: ubuntu-latest
    needs: build_apk

    steps:
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app-release

      - name: Copy APK to Output Directory
        run: |
          ls
          echo "github workspace ${{ github.workspace }}"
          ls -R ${{ github.workspace }}
          mkdir -p $GITHUB_WORKSPACE/output
          cp ${{ github.workspace }}/app-release.apk $GITHUB_WORKSPACE/output/
          # cp ${{ github.workspace }}/app-release.apk $GITHUB_WORKSPACE/output/
